const products = [
    { productId: 1, productName: 'Smartphone', productCategory: 'Electronics', productCompany: 'Apple', productPrice: 999, productRating: 4.5, productStock: 150 },
    { productId: 2, productName: 'Laptop', productCategory: 'Electronics', productCompany: 'Dell', productPrice: 1200, productRating: 4.0, productStock: 80 },
    { productId: 3, productName: 'Headphones', productCategory: 'Electronics', productCompany: 'Sony', productPrice: 200, productRating: 3.5, productStock: 220 },
    { productId: 4, productName: 'T-Shirt', productCategory: 'Clothing', productCompany: 'Nike', productPrice: 25, productRating: 4.7, productStock: 500 },
    { productId: 5, productName: 'Jeans', productCategory: 'Clothing', productCompany: 'Levi\'s', productPrice: 60, productRating: 4.3, productStock: 150 },
    { productId: 6, productName: 'Soccer Ball', productCategory: 'Sports', productCompany: 'Adidas', productPrice: 35, productRating: 4.2, productStock: 300 },
    { productId: 7, productName: 'Basketball', productCategory: 'Sports', productCompany: 'Spalding', productPrice: 45, productRating: 4.0, productStock: 180 },
    { productId: 8, productName: 'Sofa', productCategory: 'Furniture', productCompany: 'Ikea', productPrice: 400, productRating: 4.4, productStock: 60 },
    { productId: 9, productName: 'Dining Table', productCategory: 'Furniture', productCompany: 'WoodenStreet', productPrice: 350, productRating: 4.2, productStock: 75 },
    { productId: 10, productName: 'Washing Machine', productCategory: 'Home Appliances', productCompany: 'LG', productPrice: 650, productRating: 4.5, productStock: 90 },
    { productId: 11, productName: 'Refrigerator', productCategory: 'Home Appliances', productCompany: 'Samsung', productPrice: 700, productRating: 4.3, productStock: 50 },
    { productId: 12, productName: 'Air Conditioner', productCategory: 'Home Appliances', productCompany: 'Daikin', productPrice: 900, productRating: 4.6, productStock: 120 },
    { productId: 13, productName: 'Smartwatch', productCategory: 'Electronics', productCompany: 'Samsung', productPrice: 150, productRating: 4.2, productStock: 200 },
    { productId: 14, productName: 'Tablet', productCategory: 'Electronics', productCompany: 'Apple', productPrice: 600, productRating: 4.4, productStock: 180 },
    { productId: 15, productName: 'Shoes', productCategory: 'Clothing', productCompany: 'Puma', productPrice: 75, productRating: 4.1, productStock: 250 },
    { productId: 16, productName: 'Sweater', productCategory: 'Clothing', productCompany: 'H&M', productPrice: 45, productRating: 4.0, productStock: 300 },
    { productId: 17, productName: 'Baseball Glove', productCategory: 'Sports', productCompany: 'Wilson', productPrice: 90, productRating: 4.3, productStock: 150 },
    { productId: 18, productName: 'Golf Club', productCategory: 'Sports', productCompany: 'Callaway', productPrice: 250, productRating: 4.7, productStock: 120 },
    { productId: 19, productName: 'Chairs', productCategory: 'Furniture', productCompany: 'Urban Ladder', productPrice: 80, productRating: 4.0, productStock: 400 },
    { productId: 20, productName: 'Bookshelf', productCategory: 'Furniture', productCompany: 'Ikea', productPrice: 120, productRating: 4.5, productStock: 100 },
    { productId: 21, productName: 'Air Fryer', productCategory: 'Home Appliances', productCompany: 'Philips', productPrice: 180, productRating: 4.6, productStock: 90 },
    { productId: 22, productName: 'Blender', productCategory: 'Home Appliances', productCompany: 'Oster', productPrice: 50, productRating: 4.2, productStock: 300 },
    { productId: 23, productName: 'Smart TV', productCategory: 'Electronics', productCompany: 'Samsung', productPrice: 550, productRating: 4.3, productStock: 150 },
    { productId: 24, productName: 'Microwave', productCategory: 'Home Appliances', productCompany: 'Panasonic', productPrice: 100, productRating: 4.0, productStock: 250 },
    { productId: 25, productName: 'Jacket', productCategory: 'Clothing', productCompany: 'Columbia', productPrice: 90, productRating: 4.2, productStock: 200 },
    { productId: 26, productName: 'Skateboard', productCategory: 'Sports', productCompany: 'Element', productPrice: 60, productRating: 4.1, productStock: 180 },
    { productId: 27, productName: 'Cabinet', productCategory: 'Furniture', productCompany: 'Hafele', productPrice: 250, productRating: 4.3, productStock: 75 },
    { productId: 28, productName: 'Dishwasher', productCategory: 'Home Appliances', productCompany: 'Bosch', productPrice: 550, productRating: 4.4, productStock: 60 },
    { productId: 29, productName: 'Jacket', productCategory: 'Clothing', productCompany: 'North Face', productPrice: 120, productRating: 4.5, productStock: 150 },
    { productId: 30, productName: 'Bicycle', productCategory: 'Sports', productCompany: 'Trek', productPrice: 300, productRating: 4.0, productStock: 90 },
    { productId: 31, productName: 'T-Shirt', productCategory: 'Clothing', productCompany: 'Trek', productPrice: 25, productRating: 4.2, productStock: 500 }
];
